export default function ({ $axios, redirect }) {
  $axios.onError((error) => {
    const code = parseInt(error.response && error.response.status)

    console.log(1)
    console.log(1)
    console.log(1)
    console.log(1)
    console.log(1)
    console.log(1)
    console.log(1)
    console.log(1)
    console.log(1)
    console.log(1)
    console.log(1)
    console.log(1)
    console.log(1)
    console.log(1)
    console.log(1)
    console.log(1)
    console.log(1)
    console.log(1)
    console.log(1)
    console.log(1)
    console.log(1)
    console.log(1)
    console.log(1)
    console.log(1)

    console.log(1)
    if (code === 401) redirect('/login')
  })
}
